### ISSUE TITLE
Deal with messy multi fasta headers

### ISSUE THREAD

**Issue by samlipworth** [wtmatlock/flanker#38]
Currently if the multifasta header does not match the filename flanker will not work. We have provided a script as a workaround for the moment but this should be dealt with in the next release.

**Comment by samlipworth** [comment]
update to this - the problem is actually that spaces in fasta headers are a problem (unicycler has lots of these). This should be simple to fix.

**Comment by embatty** [comment]
I think checking the match on the contig ID and not description fixes this one as it doesn't check anything after the first space.

**Comment by wtmatlock** [comment]
Yup, we fixed it with exactly that earlier today, thanks! Will close this issue now.
