### ISSUE TITLE
ERROR: Gene not found in sequence. Can i add custom database? . short contigs and --window option

### ISSUE THREAD

**Issue by Leytoncito** [wtmatlock/flanker#43]
I am very interested in using this tool for my analysis, I have 3 doubts.
(1) I tried to use the command "$ flanker --flank both -w 6000 --gene emr --fasta_file all_genomas.fasta --include_gene" in my analysis, but it did not return anything, just an error:

Error: Gene erm not found in 43770.1000.con.0010
Traceback (most recent call last):
  File &quot;/home/michel/miniconda3/envs/flanker/bin/flanker&quot;, line 10, in &lt;module&gt;
    sys.exit(main())
  File &quot;/home/michel/miniconda3/envs/flanker/lib/python3.7/site-packages/flanker/flanker.py&quot;, line 383, in main
    flanker_main()
  File &quot;/home/michel/miniconda3/envs/flanker/lib/python3.7/site-packages/flanker/flanker.py&quot;, line 345, in flanker_main
    flank_fasta_file_lin(args.fasta_file, args.window,gene.strip())
  File &quot;/home/michel/miniconda3/envs/flanker/lib/python3.7/site-packages/flanker/flanker.py&quot;, line 266, in flank_fasta_file_lin
    gene_sense=str(gene_sense[&apos;STRAND&apos;].iloc[0])
  File &quot;/home/michel/miniconda3/envs/flanker/lib/python3.7/site-packages/pandas/core/indexing.py&quot;, line 895, in _getitem_
    return self._getitem_axis(maybe_callable, axis=axis)
  File &quot;/home/michel/miniconda3/envs/flanker/lib/python3.7/site-packages/pandas/core/indexing.py&quot;, line 1501, in _getitem_axis
    self._validate_integer(key, axis)
  File &quot;/home/michel/miniconda3/envs/flanker/lib/python3.7/site-packages/pandas/core/indexing.py&quot;, line 1444, in _validate_integer
    raise IndexError(&quot;single positional indexer is out-of-bounds&quot;)
IndexError: single positional indexer is out-of-bounds

It is probably because I use all my genomes (fragmented or not) are in a concatenated file. It throws an error when it cannot find the gene in some genome.
Is there a way to extract the contigs that have a gene from the genomes of interest?
It seems that we must do a previous analysis of abricate to know which contig contains the gene of interest.
(2) The second question is: if flanker uses abricate databases, then I can add more databases to abricate, for example a custom database or a database such as ISfinder or Megares,
Is the latter true? Does Flanker work this way?

It would be interesting, that Flanker has an option to add a sequence (fasta), then Flanker looks for neighboring genes to the added sequence.

(3) since genomes generally do not always have a high quality of assembly, contigs can be short, long and medium. If there is a gene of interest in a short contig, then I specify the --window 6000 option, but there is no 6000 bp on either side of the sequence. What about this? 
I appreciate the answers in advance.
Thanks a lot

**Comment by wtmatlock** [comment]
Hi, 

Thanks for getting in touch. 

1. The gene flanks will not be extracted unless your query gene name matches your database gene name: `emr` should probably be `emr-1`.  Otherwise, try using the new `--closest_match` mode, which will extract the flank for the gene with the most similar name to your query. Worth also mentioning that your .fasta header should have no whitespace, this should be fixed soon.
2. Yup, you can. Specify your database with the `--database` flag, and follow the instructions on the Abricate repo.
3. Providing you aren't running in `--circ` mode, it will truncate the flanking sequence if it exceeds the contig length (both upstream and downstream)

**Comment by samlipworth** [comment]
Yes I have just tested and flanker does work with fragmented short read assemblies (though the naming scheme is currently not ideal - we will fix this).
