### ISSUE TITLE
using draft assemblies?

### ISSUE THREAD

**Issue by jpaganini** [wtmatlock/flanker#48]
Dear William,
Thanks for developing this awesome tool, I'm sure it will prove very useful for a lot of researchers. 

I'm evaluating using Flanker for my own research, but I only posses short-read sequencing data. Therefore, I wanted to ask you: Have your tried the tool with draft assemblies? If so, how did it perform?

Thanks for your time. I'll be waiting for your answer

Cheers,

**Comment by wtmatlock** [comment]
Hi,

Glad you like the tool--Flanker seemed to work okay on shorter contigs tested for [Issue 43](https://github.com/wtmatlock/flanker/issues/43). If you have a large sample, it may be worth pre-filtering contigs e.g. Abricate output and Seqtools subseq.

Thanks,

Will and the Flanker team
