### ISSUE TITLE
Unable to update Abricate; issues after trying 

### ISSUE THREAD

**Issue by kringwa2** [wtmatlock/flanker#52]
Edit: I was able to solve this problem with help from our IT administrator.

I was originally able to set up and use abricate using these instructions from the main page:

```
conda install -c conda-forge -c bioconda -c defaults abricate
abricate --check
abricate --list
```

However, I noticed that the databases said 2018. I tried to update them using the command on the main page,

> ~/02_21_22_abricate$ abricate-get_db --db ncbi --force
> Can't locate Bio/Seq.pm in @INC (you may need to install the Bio::Seq module) (@INC contains: /data/home/user/anaconda3/lib/site_perl/5.26.2/x86_64-linux-thread-multi /data/home/user/anaconda3/lib/site_perl/5.26.2 /data/home/user/anaconda3/lib/5.26.2/x86_64-linux-thread-multi /data/home/user/anaconda3/lib/5.26.2 .) at /home/user/anaconda3/bin/abricate-get_db line 3.
> BEGIN failed--compilation aborted at /home/user/anaconda3/bin/abricate-get_db line 3.

I had the same issue both on our lab's server and on my laptop running ubuntu.

On my laptop using Ubuntu, I installed Bio::Seq. I was still running into errors so I tried the advice on this issue page:

https://github.com/tseemann/abricate/issues/174

> The problem was solved as follows:
> conda update -c conda-forge -c bioconda -c defaults abricate
> 
> If it works, be sure to update all databases
> abricate --setupdb
> 
> abricate --list

Unfortunately, I now get this response:

`abricate --check`

```
Can't locate List/MoreUtils.pm in @INC (you may need to install the List::MoreUtils module) (@INC contains: /data/home/user/anaconda3/lib/site_perl/5.26.2/x86_64-linux-thread-multi /data/home/user/anaconda3/lib/site_perl/5.26.2 /data/home/user/anaconda3/lib/5.26.2/x86_64-linux-thread-multi /data/home/user/anaconda3/lib/5.26.2 .) at /home/user/anaconda3/bin/abricate line 10.
BEGIN failed--compilation aborted at /home/user/anaconda3/bin/abricate line 10.
```

That message is from our server, but I get the same one (with different locations) on my laptop with Ubuntu. I added the List::MoreUtils module but I am still getting the same error.

Has anyone seen or solved this issue?

**Comment by samlipworth** [comment]
Looks like this is solved but please let us know if issue reccurs
